before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./
  binary: cloud-sql-proxy-v2-operator
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- tap:
    owner: TomoyukiSugiyama
    name: homebrew-cloud-sql-proxy-v2-operator
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator
  description: cloud-sql-proxy-v2-operator
  test: |
    system "#{bin}/cloud-sql-proxy-v2-operator --version"